/* ============================================================
   CORPUS — apprentissage et test
   ------------------------------------------------------------
   Chaque langue dispose de deux textes disjoints :

     TRAIN : sert à estimer les probabilités du modèle
     TEST  : jamais vu à l'apprentissage, sert à mesurer
             l'entropie croisée réelle (bits/caractère)

   Cette séparation est essentielle. Mesurer l'entropie sur le
   texte d'apprentissage donne une valeur artificiellement basse :
   le modèle a mémorisé. Seule l'évaluation sur texte inédit
   estime honnêtement Fₙ, la quantité définie par Shannon (§7,
   théorème 6). C'est exactement le protocole d'évaluation d'un
   modèle de langue moderne.

   Les textes sont des proses originales écrites pour ce projet,
   dans des registres variés (récit, description, exposé), afin
   d'offrir des statistiques représentatives de la langue.
   ============================================================ */

export const TRAIN = {
  fr: `Le matin se levait lentement sur la vallée. Une brume légère flottait au-dessus de la rivière et les premiers rayons du soleil traversaient les branches des grands chênes. Un chien aboyait quelque part derrière les maisons, puis le silence revenait, plus épais qu'avant. La femme qui habitait la dernière ferme du chemin sortit sur le pas de sa porte, regarda le ciel pendant un long moment et rentra chercher son manteau. Elle savait, à la couleur des nuages, que la pluie viendrait avant midi.
Dans le village, la boulangerie était déjà ouverte. L'odeur du pain chaud sortait par la porte entrebâillée et se répandait dans la rue étroite. Les enfants passaient en courant, leurs cartables sur le dos, et se bousculaient devant la vitrine. Le boulanger, un homme large et calme, sortait les baguettes du four avec une longue pelle de bois. Il travaillait depuis quatre heures du matin et ne s'en plaignait jamais. Chaque jour ressemblait au précédent, disait-il, et c'était précisément ce qu'il aimait dans ce métier.
La ville, plus loin, commençait à s'agiter. Les voitures remplissaient les avenues, les feux passaient du rouge au vert, les gens marchaient vite en regardant leur téléphone. Devant la gare, un vieil homme jouait de l'accordéon sans regarder personne. Une jeune femme s'arrêta, chercha une pièce dans sa poche, la posa dans l'étui ouvert et repartit sans un mot. Le musicien ne leva pas les yeux mais changea de morceau, comme pour la remercier.
Il faut du temps pour comprendre une langue. On apprend d'abord les mots, puis les règles qui les assemblent, puis les habitudes qui échappent aux règles. Une phrase correcte n'est pas toujours une phrase naturelle. Nous disons volontiers qu'il fait beau, jamais qu'il produit du beau. Nous acceptons une grande maison blanche, mais une blanche grande maison nous heurte immédiatement. Personne n'a jamais appris cette contrainte explicitement : elle s'installe par l'usage, à force d'entendre et de lire.
Cette régularité profonde a une conséquence remarquable. Lorsque nous lisons, nous devinons constamment la suite sans nous en apercevoir. Après une préposition nous attendons un groupe nominal, après un sujet nous attendons un verbe, après la lettre q nous attendons presque toujours un u. Le texte que nos yeux parcourent contient donc beaucoup moins d'information nouvelle qu'il n'y paraît. Une bonne partie de ce que nous lisons ne fait que confirmer ce que nous avions déjà anticipé.
Les mathématiciens ont trouvé le moyen de mesurer cette anticipation. On considère chaque lettre comme le résultat d'un tirage, on note la probabilité de chaque résultat possible, et l'on calcule la surprise moyenne. Cette surprise moyenne porte le nom d'entropie. Si le texte est parfaitement imprévisible, l'entropie est maximale. S'il est parfaitement prévisible, elle est nulle. Toutes les langues humaines se situent quelque part entre ces deux extrêmes, et beaucoup plus près de la prévisibilité qu'on ne l'imagine.
La conséquence pratique est immense. Puisque le texte est prévisible, il est compressible. Puisqu'il est redondant, il résiste au bruit. Une lettre effacée se devine, une faute de frappe se corrige, une conversation se suit dans un train bruyant. Nous ne remarquons jamais ce travail parce qu'il se fait sans effort, mais il repose entièrement sur la structure statistique de la langue que nous avons apprise.
Le soir tombait quand ils arrivèrent enfin au bord du lac. L'eau était immobile et reflétait les montagnes sombres. Ils posèrent leurs sacs sur l'herbe, s'assirent côte à côte et ne dirent rien pendant plusieurs minutes. Le vent s'était arrêté. Une barque abandonnée cognait doucement contre le ponton de bois. Plus tard, quand la nuit fut complète, ils allumèrent un petit feu et regardèrent les étincelles monter vers les étoiles.
Le professeur écrivit trois lignes au tableau et se retourna vers la classe. Personne ne comprenait encore, et c'était normal. Il reprit depuis le début, plus lentement, avec un exemple simple. Une élève leva la main et posa une question que tout le monde se posait sans oser la formuler. La réponse éclaira soudain l'ensemble du raisonnement. On entendit plusieurs stylos recommencer à écrire en même temps.
La mémoire fonctionne un peu de la même manière. Nous ne retenons pas chaque détail, nous retenons la structure et nous reconstruisons le reste. C'est pourquoi nous nous souvenons du sens d'une phrase longtemps après avoir oublié ses mots exacts. Ce que nous stockons, ce n'est pas le texte, c'est ce que le texte avait d'imprévisible. Le reste, la grammaire le régénère toute seule.
Il pleuvait depuis trois jours et la route était devenue impraticable. Les habitants du hameau attendaient sans impatience, habitués à ces épisodes. On se prêtait du bois, on partageait la soupe, on parlait devant la fenêtre en regardant l'eau descendre le long du chemin. Le facteur ne montait plus. La radio annonçait une amélioration pour le lendemain, mais personne n'y croyait vraiment.
Ce que nous appelons comprendre une phrase est peut-être d'abord la capacité de prévoir sa suite. Un modèle statistique qui apprend à prédire le mot suivant finit par représenter, sans qu'on le lui demande, la grammaire, le vocabulaire, les tournures et même certaines connaissances sur le monde. La prédiction n'est pas un objectif modeste : c'est probablement le plus exigeant de tous, car pour bien prédire il faut à peu près tout savoir du texte qui précède.
Tu viens avec nous ou tu restes ici ? demanda-t-elle en fermant son sac. Je ne sais pas encore, répondit-il sans lever la tête. Décide-toi vite, le bus part dans un quart d'heure et il n'y en aura pas d'autre avant demain matin. Il regarda la fenêtre, puis la table, puis ses mains. D'accord, dit-il enfin, je viens, mais je ne reste pas longtemps. Elle sourit sans rien ajouter et lui tendit son manteau.
Le corps humain contient environ soixante mille kilomètres de vaisseaux sanguins. Le cœur pompe chaque jour près de sept mille litres de sang, sans repos, pendant toute une vie. Les poumons échangent l'oxygène et le gaz carbonique à travers une surface équivalente à celle d'un court de tennis. Ces chiffres surprennent toujours, mais ils décrivent un fonctionnement parfaitement ordinaire, celui de chaque personne qui marche dans la rue.
Le conseil municipal s'est réuni jeudi soir pour examiner le budget de l'année prochaine. Les travaux de la place centrale, longtemps repoussés, devraient commencer au printemps. Plusieurs habitants sont venus poser des questions sur le stationnement et sur la fermeture de la petite école. Le maire a promis une réunion publique avant la fin du mois. La séance s'est terminée un peu après vingt-deux heures.
Prenez trois cents grammes de farine, une pincée de sel, deux œufs et un demi-litre de lait. Mélangez d'abord la farine et le sel, creusez un puits au centre, cassez les œufs dedans et remuez doucement en versant le lait petit à petit. Laissez reposer la pâte une heure au frais. Faites chauffer une poêle, graissez-la légèrement et versez une petite louche en tournant le poignet pour étaler.
Les océans couvrent plus des deux tiers de la surface de la planète et absorbent une part considérable de la chaleur accumulée dans l'atmosphère. Leur température monte lentement mais régulièrement, ce qui modifie les courants, déplace les bancs de poissons et fragilise les récifs. Les scientifiques mesurent ces variations depuis des bouées, des navires et des satellites, puis comparent les résultats à des modèles numériques de plus en plus précis.
Il faut imaginer un très grand livre dans lequel toutes les phrases possibles seraient écrites. La plupart de ces phrases seraient du charabia, quelques-unes seraient grammaticales, une infime minorité aurait un sens. Écrire, c'est se déplacer dans ce livre en suivant des chemins étroits. Ce sont ces chemins, et non les mots eux-mêmes, que la statistique parvient à décrire.
Le train est parti à sept heures du matin. Il faisait encore nuit sur le quai et les lampes jetaient une lumière jaune sur le béton mouillé. Une dizaine de personnes attendaient en silence, le col relevé, les mains dans les poches. Quand les portes se sont ouvertes, tout le monde est monté sans se presser. Le contrôleur est passé une heure plus tard, il a regardé les billets sans rien dire et il est reparti vers l'avant du train. Les champs défilaient derrière la vitre, gris et plats, coupés par des rangées d'arbres nus. Une femme lisait un journal, un homme dormait la tête contre la fenêtre, un enfant demandait toutes les cinq minutes combien de temps il restait.
Il a plu toute la semaine et le jardin est devenu impraticable. La terre colle aux chaussures, les allées ont disparu sous l'eau, et les rosiers que nous avions taillés en février commencent à peine à repartir. Mon père disait qu'un jardin demande de la patience plus que de la force. Il passait ses dimanches à bêcher, à semer, à regarder pousser des choses qu'il ne verrait pas fleurir avant l'année suivante. Je n'ai compris que très tard ce qu'il trouvait à cette lenteur. Aujourd'hui je fais la même chose, avec les mêmes outils, dans le même désordre, et cela me convient parfaitement.
La cuisine est la pièce où tout le monde finit par se retrouver. On y entre pour boire un verre d'eau et on y reste une heure. Il y a la table, les chaises dépareillées, le bruit du réfrigérateur, la fenêtre qui donne sur la cour. C'est là que se disent les choses importantes, presque toujours de biais, entre deux gestes, pendant qu'on épluche des légumes ou qu'on essuie une assiette. Personne ne s'assoit jamais pour annoncer une nouvelle. On la glisse dans la conversation, on attend la réaction, on continue de couper les oignons.
Le corps garde la mémoire des gestes longtemps après que la tête les a oubliés. On remonte sur un vélo après quinze ans et l'équilibre revient en trois mètres. On retrouve un clavier et les doigts savent où aller avant qu'on ait pensé aux lettres. Cette mémoire-là ne passe pas par les mots. Elle s'installe par la répétition, elle résiste à l'oubli, et elle explique pourquoi apprendre lentement vaut souvent mieux qu'apprendre vite.
Les chiffres du mois dernier montrent une hausse modérée de la consommation, portée surtout par les services. L'industrie reste stable, la construction recule légèrement pour le troisième trimestre consécutif. Les prix continuent d'augmenter mais moins vite qu'au début de l'année. Les économistes interrogés restent prudents : ils rappellent que ces variations sont faibles, que les révisions sont fréquentes, et qu'il faut plusieurs trimestres avant de parler d'une tendance.
Il y a deux façons d'écouter de la musique. On peut la mettre en fond, pendant qu'on travaille, et la laisser occuper l'espace sans y penser. On peut aussi s'asseoir, ne rien faire d'autre, et suivre ce qui se passe. La deuxième façon demande un effort que nous prenons de moins en moins souvent. Pourtant c'est la seule qui permette d'entendre la construction d'un morceau, les reprises, les silences, ce moment où un instrument entre alors qu'on ne l'attendait plus.
La montagne change complètement selon l'heure. Le matin, l'air est net, les crêtes se découpent, on voit à trente kilomètres. Vers midi tout s'aplatit, les couleurs se délavent, la chaleur monte des pierres. Le soir, l'ombre remonte les versants et les sommets restent éclairés longtemps après que la vallée est passée dans le bleu. Ceux qui marchent tôt le savent : la même montée n'a rien à voir à six heures et à quatorze heures.
Un bon professeur ne donne pas la réponse. Il pose la question qui permet de la trouver, puis il attend. Cette attente est la partie difficile du métier, parce qu'elle ressemble à de l'inaction et qu'elle est en réalité le travail lui-même. Expliquer trop vite prive l'élève du seul moment qui compte, celui où quelque chose se met en place tout seul. On croit gagner du temps, on en fait perdre.
Le sommeil occupe un tiers de notre vie et nous ne savons toujours pas exactement à quoi il sert. Ce qui est certain, c'est que le priver de quelques heures dégrade l'attention, l'humeur et la mémoire de façon mesurable dès le lendemain. Pendant la nuit, le cerveau ne s'éteint pas : il rejoue, il trie, il consolide. Les souvenirs de la journée sont repris, comparés, parfois effacés. Nous nous réveillons avec une version simplifiée de la veille.
Ce que l'on appelle une habitude est une décision qu'on ne prend plus. Au début il faut y penser, se forcer, résister à l'envie de faire autre chose. Puis le geste s'installe, le coût mental diminue, et un jour on s'aperçoit qu'on l'a fait sans y penser. C'est pour cela que les habitudes sont si difficiles à changer : ce n'est pas la volonté qui manque, c'est que la décision n'est plus consciente.
Le marché du samedi commence à sept heures et se vide vers treize heures. Les producteurs arrivent les premiers, déchargent les cageots, installent les balances. Vers neuf heures il y a foule, on se croise, on se salue, on fait la queue devant les mêmes trois stands. Les prix ne sont pas affichés partout et personne ne s'en plaint. À midi les invendus commencent à baisser et les habitués attendent ce moment précis pour acheter.
Apprendre une langue étrangère, c'est accepter de mal parler pendant longtemps. Cette période est désagréable et elle est obligatoire. On comprend avant de parler, on lit avant d'écrire, on reconnaît avant de produire. Ceux qui progressent vite ne sont pas ceux qui ont le plus de mémoire, mais ceux qui acceptent le plus de fautes. Chaque phrase ratée corrige un peu le modèle interne que nous construisons sans le savoir.
La lumière du nord est stable, celle du sud change toute la journée. Les peintres le savent depuis toujours et choisissent leurs ateliers en fonction. Une fenêtre au nord donne une lumière égale, un peu froide, qui ne bouge pas entre dix heures et seize heures. Au sud, il faut filtrer, ajuster, recommencer. Ce détail de construction a décidé de l'emplacement de milliers d'ateliers depuis quatre siècles.
On dit souvent qu'une image vaut mille mots. C'est vrai pour décrire un visage et complètement faux pour exprimer une condition, une négation ou un doute. Aucune image ne dit « si », ni « pas encore », ni « à moins que ». Le langage a inventé des outils que le dessin ne possède pas, et c'est pour cela que nous n'avons jamais cessé d'écrire alors même que nous savions dessiner bien avant.`,

  en: `The morning came slowly over the valley. A thin mist floated above the river and the first rays of the sun cut through the branches of the old oaks. A dog barked somewhere behind the houses, and then the silence returned, deeper than before. The woman who lived in the last farm along the road stepped outside, looked at the sky for a long moment, and went back in to fetch her coat. She knew from the colour of the clouds that the rain would arrive before noon.
In the village the bakery was already open. The smell of warm bread came through the half open door and spread down the narrow street. Children ran past with their bags on their backs and crowded in front of the window. The baker, a broad and quiet man, pulled the loaves from the oven with a long wooden peel. He had been working since four in the morning and never complained about it. Every day was like the one before, he said, and that was exactly what he liked about the trade.
Further away the city was beginning to stir. Cars filled the avenues, the lights turned from red to green, people walked quickly while looking at their phones. In front of the station an old man played the accordion without looking at anyone. A young woman stopped, found a coin in her pocket, placed it in the open case and walked away without a word. The musician did not raise his eyes but changed the tune, as if to thank her.
It takes time to understand a language. First you learn the words, then the rules that join them, then the habits that escape the rules. A correct sentence is not always a natural one. We happily say that it is raining, never that it produces rain. We accept a large white house, but a white large house strikes the ear immediately. Nobody was ever taught that constraint explicitly. It settles in through use, from hearing and reading again and again.
This deep regularity has a remarkable consequence. When we read, we are constantly guessing what comes next without noticing it. After a preposition we expect a noun phrase, after a subject we expect a verb, after the letter q we almost always expect a u. The text our eyes travel across therefore carries far less new information than it appears to. A large part of what we read merely confirms what we had already anticipated.
Mathematicians found a way to measure that anticipation. We treat each letter as the outcome of a draw, we write down the probability of every possible outcome, and we compute the average surprise. That average surprise is called entropy. If the text is perfectly unpredictable the entropy is maximal. If it is perfectly predictable the entropy is zero. Every human language sits somewhere between these two extremes, and much closer to predictability than one would think.
The practical consequence is enormous. Because text is predictable it can be compressed. Because it is redundant it resists noise. A missing letter can be guessed, a typing mistake can be corrected, a conversation can be followed on a noisy train. We never notice this work because it costs us no effort, yet it rests entirely on the statistical structure of the language we have learned.
Evening was falling when they finally reached the shore of the lake. The water lay still and reflected the dark mountains. They put their bags down on the grass, sat side by side and said nothing for several minutes. The wind had dropped. An abandoned boat knocked gently against the wooden pier. Later, when the night was complete, they lit a small fire and watched the sparks rise towards the stars.
The teacher wrote three lines on the board and turned back to the class. Nobody understood yet, and that was normal. He started again from the beginning, more slowly, with a simple example. A student raised her hand and asked the question everyone had been asking silently. The answer suddenly lit up the whole argument. Several pens could be heard starting to write again at the same time.
Memory works in much the same way. We do not store every detail, we store the structure and rebuild the rest. That is why we remember the meaning of a sentence long after forgetting its exact words. What we keep is not the text but whatever the text contained that was unpredictable. The rest is regenerated by grammar on its own.
It had been raining for three days and the road had become impassable. The people of the hamlet waited without impatience, used to such spells. They lent each other wood, shared soup, and talked by the window while watching the water run down the path. The postman no longer came up. The radio promised an improvement for the next day, but nobody really believed it.
What we call understanding a sentence may first of all be the ability to predict how it continues. A statistical model trained to predict the next word ends up representing, without being asked, the grammar, the vocabulary, the idioms and even some knowledge about the world. Prediction is not a modest objective. It is probably the most demanding of all, because to predict well you must know almost everything about the text that came before.
Are you coming with us or are you staying here, she asked while closing her bag. I do not know yet, he answered without lifting his head. Make up your mind quickly, the bus leaves in a quarter of an hour and there will not be another one before tomorrow morning. He looked at the window, then at the table, then at his hands. All right, he said at last, I am coming, but I am not staying long. She smiled without adding anything and handed him his coat.
The human body contains about sixty thousand kilometres of blood vessels. Every day the heart pumps nearly seven thousand litres of blood, without rest, for an entire lifetime. The lungs exchange oxygen and carbon dioxide across a surface roughly the size of a tennis court. These figures are always surprising, yet they describe a perfectly ordinary machine, the one carried by every person walking down the street.
The town council met on Thursday evening to examine next year's budget. The works on the central square, postponed for a long time, should begin in the spring. Several residents came to ask questions about parking and about the closing of the small school. The mayor promised a public meeting before the end of the month. The session ended a little after ten o'clock.
Take three hundred grams of flour, a pinch of salt, two eggs and half a litre of milk. First mix the flour and the salt, hollow out a well in the centre, break the eggs into it and stir gently while pouring the milk little by little. Let the batter rest for an hour in a cool place. Heat a pan, grease it lightly and pour in a small ladle, turning your wrist to spread it.
The oceans cover more than two thirds of the surface of the planet and absorb a considerable share of the heat accumulating in the atmosphere. Their temperature rises slowly but steadily, which changes currents, moves fish stocks and weakens reefs. Scientists measure these variations from buoys, ships and satellites, and then compare the results with numerical models of increasing precision.
Imagine a very large book in which every possible sentence has been written down. Most of those sentences would be gibberish, a few would be grammatical, and a tiny minority would mean something. Writing is moving through that book along narrow paths. It is those paths, rather than the words themselves, that statistics manages to describe.
The train left at seven in the morning. It was still dark on the platform and the lamps threw a yellow light on the wet concrete. A dozen people waited in silence, collars up, hands in their pockets. When the doors opened everyone got on without hurrying. The conductor came through an hour later, looked at the tickets without saying anything, and went back towards the front of the train. The fields went past behind the window, grey and flat, cut by rows of bare trees. A woman was reading a newspaper, a man slept with his head against the glass, a child asked every five minutes how long was left.
It has rained all week and the garden has become impassable. The soil sticks to your shoes, the paths have disappeared under water, and the roses we pruned in February are only just starting again. My father used to say that a garden asks for patience rather than strength. He spent his Sundays digging, sowing, watching things grow that he would not see flower before the following year. I only understood much later what he found in that slowness. Today I do the same thing, with the same tools, in the same mess, and it suits me perfectly.
The kitchen is the room where everyone ends up. You go in for a glass of water and you stay an hour. There is the table, the mismatched chairs, the noise of the fridge, the window looking onto the yard. That is where the important things get said, almost always sideways, between two gestures, while somebody peels vegetables or dries a plate. Nobody ever sits down to announce news. They slip it into the conversation, wait for the reaction, and go on cutting the onions.
The body keeps the memory of movements long after the head has forgotten them. You get back on a bicycle after fifteen years and the balance returns within three metres. You find a keyboard and your fingers know where to go before you have thought about the letters. That kind of memory does not pass through words. It settles in through repetition, it resists forgetting, and it explains why learning slowly is often better than learning fast.
Last month's figures show a moderate rise in consumption, driven mainly by services. Industry remains stable, construction falls slightly for the third quarter in a row. Prices continue to rise but more slowly than at the start of the year. The economists we asked remain cautious: they point out that these variations are small, that revisions are frequent, and that several quarters are needed before speaking of a trend.
There are two ways of listening to music. You can put it on in the background, while working, and let it fill the space without thinking about it. You can also sit down, do nothing else, and follow what happens. The second way asks for an effort we make less and less often. Yet it is the only one that lets you hear how a piece is built, the repeats, the silences, that moment when an instrument comes in when you had stopped expecting it.
The mountain changes completely depending on the hour. In the morning the air is sharp, the ridges stand out, you can see thirty kilometres. Around noon everything flattens, the colours wash out, heat rises from the stones. In the evening the shadow climbs the slopes and the summits stay lit long after the valley has turned blue. Those who walk early know it: the same climb has nothing in common at six in the morning and at two in the afternoon.
A good teacher does not give the answer. He asks the question that makes it possible to find it, and then he waits. That waiting is the hard part of the job, because it looks like doing nothing and is in fact the work itself. Explaining too quickly robs the student of the only moment that counts, the one where something falls into place on its own. You think you are saving time; you are making people lose it.
Sleep takes up a third of our lives and we still do not know exactly what it is for. What is certain is that taking a few hours away from it measurably damages attention, mood and memory by the next day. During the night the brain does not switch off: it replays, it sorts, it consolidates. The memories of the day are taken up again, compared, sometimes erased. We wake with a simplified version of yesterday.
What we call a habit is a decision we no longer make. At the start you have to think about it, force yourself, resist the urge to do something else. Then the movement settles in, the mental cost falls, and one day you notice you have done it without thinking. That is why habits are so hard to change: it is not willpower that is missing, it is that the decision is no longer conscious.
The Saturday market starts at seven and empties out around one. The growers arrive first, unload the crates, set up the scales. By nine it is crowded, people cross, greet each other, queue at the same three stalls. Prices are not displayed everywhere and nobody complains. By midday the unsold goods start coming down in price and the regulars wait for exactly that moment to buy.
Learning a foreign language means accepting that you will speak badly for a long time. That period is unpleasant and it is compulsory. You understand before you speak, you read before you write, you recognise before you produce. Those who make progress quickly are not the ones with the best memory, but the ones who accept the most mistakes. Every failed sentence slightly corrects the internal model we build without knowing it.
Northern light is steady, southern light changes all day. Painters have known this forever and choose their studios accordingly. A window facing north gives an even, slightly cold light that does not move between ten and four. Facing south you have to filter, adjust, start again. That building detail has decided the location of thousands of studios over four centuries.
People often say a picture is worth a thousand words. That is true for describing a face and completely false for expressing a condition, a negation or a doubt. No picture says if, or not yet, or unless. Language invented tools that drawing does not have, and that is why we never stopped writing even though we could draw long before.`,

  es: `La mañana llegaba despacio sobre el valle. Una niebla ligera flotaba encima del río y los primeros rayos del sol atravesaban las ramas de los viejos robles. Un perro ladraba en algún lugar detrás de las casas, y después volvía el silencio, más espeso que antes. La mujer que vivía en la última granja del camino salió a la puerta, miró el cielo durante un largo rato y entró a buscar su abrigo. Sabía, por el color de las nubes, que la lluvia llegaría antes del mediodía.
En el pueblo la panadería ya estaba abierta. El olor del pan caliente salía por la puerta entreabierta y se extendía por la calle estrecha. Los niños pasaban corriendo con las mochilas a la espalda y se empujaban delante del escaparate. El panadero, un hombre ancho y tranquilo, sacaba las barras del horno con una pala larga de madera. Trabajaba desde las cuatro de la mañana y nunca se quejaba. Cada día se parecía al anterior, decía, y eso era justamente lo que le gustaba del oficio.
Más lejos la ciudad empezaba a moverse. Los coches llenaban las avenidas, los semáforos pasaban del rojo al verde, la gente caminaba deprisa mirando el teléfono. Delante de la estación un hombre mayor tocaba el acordeón sin mirar a nadie. Una mujer joven se detuvo, buscó una moneda en el bolsillo, la dejó en el estuche abierto y siguió su camino sin decir nada. El músico no levantó los ojos pero cambió de melodía, como para darle las gracias.
Hace falta tiempo para entender una lengua. Primero se aprenden las palabras, después las reglas que las unen, después las costumbres que escapan a las reglas. Una frase correcta no siempre es una frase natural. Decimos sin problema que hace frío, nunca que produce frío. Aceptamos una casa blanca grande, pero una grande blanca casa choca inmediatamente. Nadie ha aprendido nunca esa restricción de manera explícita: se instala con el uso, a fuerza de oír y de leer.
Esta regularidad profunda tiene una consecuencia notable. Cuando leemos, adivinamos constantemente lo que viene después sin darnos cuenta. Después de una preposición esperamos un sustantivo, después de un sujeto esperamos un verbo, después de la letra q esperamos casi siempre una u. El texto que recorren nuestros ojos contiene por tanto mucha menos información nueva de lo que parece. Buena parte de lo que leemos solo confirma lo que ya habíamos anticipado.
Los matemáticos encontraron la manera de medir esa anticipación. Se considera cada letra como el resultado de un sorteo, se anota la probabilidad de cada resultado posible y se calcula la sorpresa media. Esa sorpresa media se llama entropía. Si el texto es totalmente imprevisible, la entropía es máxima. Si es totalmente previsible, es nula. Todas las lenguas humanas se sitúan entre esos dos extremos, y mucho más cerca de la previsibilidad de lo que se imagina.
La consecuencia práctica es enorme. Como el texto es previsible, se puede comprimir. Como es redundante, resiste al ruido. Una letra borrada se adivina, un error de tecleo se corrige, una conversación se sigue en un tren ruidoso. Nunca notamos ese trabajo porque no nos cuesta esfuerzo, pero descansa por completo sobre la estructura estadística de la lengua que hemos aprendido.
Caía la tarde cuando llegaron por fin a la orilla del lago. El agua estaba inmóvil y reflejaba las montañas oscuras. Dejaron las mochilas sobre la hierba, se sentaron uno al lado del otro y no dijeron nada durante varios minutos. El viento se había parado. Una barca abandonada golpeaba suavemente contra el embarcadero de madera. Más tarde, cuando la noche fue completa, encendieron un fuego pequeño y miraron subir las chispas hacia las estrellas.
El profesor escribió tres líneas en la pizarra y se volvió hacia la clase. Todavía nadie entendía, y era normal. Empezó otra vez desde el principio, más despacio, con un ejemplo sencillo. Una alumna levantó la mano e hizo la pregunta que todos se hacían sin atreverse a formularla. La respuesta iluminó de golpe todo el razonamiento. Se oyeron varios bolígrafos volver a escribir al mismo tiempo.
La memoria funciona de una manera parecida. No guardamos cada detalle, guardamos la estructura y reconstruimos el resto. Por eso recordamos el sentido de una frase mucho después de haber olvidado sus palabras exactas. Lo que almacenamos no es el texto, sino lo que el texto tenía de imprevisible. El resto lo regenera la gramática sola.
Llovía desde hacía tres días y el camino se había vuelto intransitable. Los habitantes de la aldea esperaban sin impaciencia, acostumbrados a esos episodios. Se prestaban leña, compartían la sopa, hablaban junto a la ventana mirando bajar el agua por el sendero. El cartero ya no subía. La radio anunciaba una mejora para el día siguiente, pero nadie se lo creía del todo.
Lo que llamamos entender una frase quizá sea antes que nada la capacidad de prever cómo continúa. Un modelo estadístico entrenado para predecir la palabra siguiente acaba representando, sin que se lo pidan, la gramática, el vocabulario, los giros e incluso ciertos conocimientos sobre el mundo. Predecir no es un objetivo modesto: probablemente sea el más exigente de todos, porque para predecir bien hay que saber casi todo del texto anterior.
¿Vienes con nosotros o te quedas aquí?, preguntó ella mientras cerraba el bolso. Todavía no lo sé, respondió él sin levantar la cabeza. Decídete rápido, el autobús sale dentro de un cuarto de hora y no habrá otro hasta mañana por la mañana. Él miró la ventana, luego la mesa, luego sus manos. De acuerdo, dijo por fin, voy, pero no me quedo mucho tiempo. Ella sonrió sin añadir nada y le tendió el abrigo.
El cuerpo humano contiene unos sesenta mil kilómetros de vasos sanguíneos. Cada día el corazón bombea cerca de siete mil litros de sangre, sin descanso, durante toda una vida. Los pulmones intercambian oxígeno y dióxido de carbono a través de una superficie parecida a la de una pista de tenis. Estas cifras siempre sorprenden, pero describen un funcionamiento completamente ordinario, el de cualquier persona que camina por la calle.
El ayuntamiento se reunió el jueves por la tarde para examinar el presupuesto del año próximo. Las obras de la plaza central, aplazadas durante mucho tiempo, deberían empezar en primavera. Varios vecinos vinieron a preguntar por el aparcamiento y por el cierre de la escuela pequeña. El alcalde prometió una reunión pública antes de fin de mes. La sesión terminó poco después de las diez.
Coge trescientos gramos de harina, una pizca de sal, dos huevos y medio litro de leche. Mezcla primero la harina y la sal, haz un hueco en el centro, casca los huevos dentro y remueve despacio mientras viertes la leche poco a poco. Deja reposar la masa una hora en un sitio fresco. Calienta una sartén, úntala ligeramente y vierte un cucharón pequeño girando la muñeca para extenderla.
Los océanos cubren más de dos tercios de la superficie del planeta y absorben una parte considerable del calor acumulado en la atmósfera. Su temperatura sube despacio pero de manera constante, lo que modifica las corrientes, desplaza los bancos de peces y debilita los arrecifes. Los científicos miden estas variaciones desde boyas, barcos y satélites, y después comparan los resultados con modelos numéricos cada vez más precisos.
Hay que imaginar un libro enorme en el que estuvieran escritas todas las frases posibles. La mayoría serían un galimatías, unas pocas serían gramaticales y una minoría mínima tendría sentido. Escribir es desplazarse por ese libro siguiendo caminos estrechos. Son esos caminos, y no las palabras en sí, lo que la estadística consigue describir.
El tren salió a las siete de la mañana. Todavía era de noche en el andén y las lámparas echaban una luz amarilla sobre el hormigón mojado. Una docena de personas esperaba en silencio, con el cuello subido y las manos en los bolsillos. Cuando se abrieron las puertas todos subieron sin prisa. El revisor pasó una hora más tarde, miró los billetes sin decir nada y volvió hacia la cabeza del tren. Los campos desfilaban detrás del cristal, grises y planos, cortados por hileras de árboles desnudos. Una mujer leía un periódico, un hombre dormía con la cabeza contra la ventana, un niño preguntaba cada cinco minutos cuánto faltaba.
Ha llovido toda la semana y el jardín se ha vuelto intransitable. La tierra se pega a los zapatos, los senderos han desaparecido bajo el agua y los rosales que podamos en febrero apenas empiezan a brotar. Mi padre decía que un jardín pide paciencia más que fuerza. Pasaba los domingos cavando, sembrando, mirando crecer cosas que no vería florecer hasta el año siguiente. Solo mucho después entendí lo que encontraba en esa lentitud. Hoy hago lo mismo, con las mismas herramientas, en el mismo desorden, y me viene muy bien.
La cocina es la habitación donde todo el mundo acaba encontrándose. Entras a beber un vaso de agua y te quedas una hora. Están la mesa, las sillas descabaladas, el ruido de la nevera, la ventana que da al patio. Ahí se dicen las cosas importantes, casi siempre de lado, entre dos gestos, mientras alguien pela verduras o seca un plato. Nadie se sienta nunca para anunciar una noticia. La desliza en la conversación, espera la reacción y sigue cortando las cebollas.
El cuerpo guarda la memoria de los gestos mucho después de que la cabeza los haya olvidado. Vuelves a subir a una bicicleta después de quince años y el equilibrio regresa en tres metros. Encuentras un teclado y los dedos saben adónde ir antes de que hayas pensado en las letras. Esa memoria no pasa por las palabras. Se instala con la repetición, resiste al olvido y explica por qué aprender despacio suele valer más que aprender deprisa.
Las cifras del mes pasado muestran una subida moderada del consumo, impulsada sobre todo por los servicios. La industria se mantiene estable y la construcción retrocede ligeramente por tercer trimestre consecutivo. Los precios siguen subiendo pero más despacio que a principios de año. Los economistas consultados se mantienen prudentes: recuerdan que estas variaciones son pequeñas, que las revisiones son frecuentes y que hacen falta varios trimestres antes de hablar de una tendencia.
Hay dos maneras de escuchar música. Puedes ponerla de fondo, mientras trabajas, y dejar que ocupe el espacio sin pensar en ella. También puedes sentarte, no hacer nada más y seguir lo que ocurre. La segunda manera exige un esfuerzo que hacemos cada vez menos. Sin embargo es la única que permite oír cómo está construida una pieza, las repeticiones, los silencios, ese momento en que entra un instrumento cuando ya no lo esperabas.
La montaña cambia por completo según la hora. Por la mañana el aire está limpio, las crestas se recortan, se ve a treinta kilómetros. Hacia el mediodía todo se aplana, los colores se lavan, el calor sube de las piedras. Por la tarde la sombra remonta las laderas y las cumbres siguen iluminadas mucho después de que el valle haya pasado al azul. Quien camina temprano lo sabe: la misma subida no tiene nada que ver a las seis y a las dos.
Un buen profesor no da la respuesta. Hace la pregunta que permite encontrarla y luego espera. Esa espera es la parte difícil del oficio, porque parece inacción y en realidad es el trabajo mismo. Explicar demasiado pronto priva al alumno del único momento que cuenta, aquel en que algo encaja solo. Crees ganar tiempo y haces perder el tuyo y el suyo.
El sueño ocupa un tercio de nuestra vida y todavía no sabemos exactamente para qué sirve. Lo que es seguro es que quitarle unas horas degrada la atención, el humor y la memoria de forma medible al día siguiente. Durante la noche el cerebro no se apaga: repite, ordena, consolida. Los recuerdos del día se retoman, se comparan, a veces se borran. Nos despertamos con una versión simplificada de la víspera.
Lo que llamamos costumbre es una decisión que ya no tomamos. Al principio hay que pensarlo, obligarse, resistir las ganas de hacer otra cosa. Después el gesto se instala, el coste mental baja y un día te das cuenta de que lo has hecho sin pensar. Por eso las costumbres son tan difíciles de cambiar: no falta voluntad, es que la decisión ya no es consciente.
El mercado del sábado empieza a las siete y se vacía hacia la una. Los productores llegan primero, descargan las cajas, montan las balanzas. Hacia las nueve hay gentío, la gente se cruza, se saluda, hace cola en los mismos tres puestos. Los precios no están puestos en todas partes y nadie se queja. A mediodía lo que no se ha vendido empieza a bajar y los habituales esperan justo ese momento para comprar.
Aprender un idioma extranjero es aceptar hablar mal durante mucho tiempo. Ese periodo es desagradable y es obligatorio. Se entiende antes de hablar, se lee antes de escribir, se reconoce antes de producir. Los que avanzan deprisa no son los que más memoria tienen, sino los que aceptan más errores. Cada frase fallida corrige un poco el modelo interno que construimos sin saberlo.
La luz del norte es estable, la del sur cambia todo el día. Los pintores lo saben desde siempre y eligen sus talleres en consecuencia. Una ventana al norte da una luz igual, algo fría, que no se mueve entre las diez y las cuatro. Al sur hay que filtrar, ajustar, empezar otra vez. Ese detalle de construcción ha decidido la ubicación de miles de talleres durante cuatro siglos.
Se dice a menudo que una imagen vale más que mil palabras. Es cierto para describir una cara y completamente falso para expresar una condición, una negación o una duda. Ninguna imagen dice si, ni todavía no, ni a menos que. El lenguaje inventó herramientas que el dibujo no tiene, y por eso nunca dejamos de escribir aunque supiéramos dibujar mucho antes.`,

  ru: `Утро медленно поднималось над долиной. Лёгкий туман плыл над рекой, и первые лучи солнца проходили сквозь ветви старых дубов. Где-то за домами лаяла собака, потом снова возвращалась тишина, ещё более плотная, чем прежде. Женщина, жившая на последней ферме у дороги, вышла на порог, долго смотрела на небо и вернулась за пальто. По цвету облаков она знала, что дождь придёт до полудня.
В деревне пекарня была уже открыта. Запах горячего хлеба выходил через приоткрытую дверь и разносился по узкой улице. Дети пробегали мимо с рюкзаками за спиной и толкались перед витриной. Пекарь, широкий и спокойный человек, доставал хлеб из печи длинной деревянной лопатой. Он работал с четырёх часов утра и никогда не жаловался. Каждый день похож на предыдущий, говорил он, и именно это ему нравилось в его ремесле.
Дальше начинал двигаться город. Машины заполняли проспекты, светофоры менялись с красного на зелёный, люди быстро шли, глядя в телефон. Перед вокзалом пожилой человек играл на аккордеоне, ни на кого не глядя. Молодая женщина остановилась, нашла монету в кармане, положила её в открытый футляр и пошла дальше, не сказав ни слова. Музыкант не поднял глаз, но сменил мелодию, словно благодарил её.
Чтобы понять язык, нужно время. Сначала учат слова, потом правила, которые их соединяют, потом привычки, которые ускользают от правил. Правильная фраза не всегда естественная фраза. Мы спокойно говорим, что идёт дождь, но никогда не говорим, что он производит дождь. Мы принимаем большой белый дом, но белый большой дом сразу режет слух. Никто никогда не учил этому ограничению прямо: оно устанавливается через употребление, от постоянного слушания и чтения.
У этой глубокой закономерности есть замечательное следствие. Когда мы читаем, мы постоянно угадываем продолжение, сами того не замечая. После предлога мы ждём существительное, после подлежащего мы ждём сказуемое, после буквы ч мы почти всегда ждём гласную. Поэтому текст, по которому бегут наши глаза, несёт гораздо меньше новой информации, чем кажется. Значительная часть того, что мы читаем, лишь подтверждает то, что мы уже предвидели.
Математики нашли способ измерить это предвидение. Каждую букву рассматривают как результат случайного выбора, записывают вероятность каждого возможного исхода и вычисляют среднюю неожиданность. Эта средняя неожиданность называется энтропией. Если текст совершенно непредсказуем, энтропия максимальна. Если он совершенно предсказуем, она равна нулю. Все человеческие языки находятся между этими двумя крайностями и гораздо ближе к предсказуемости, чем принято думать.
Практическое следствие огромно. Раз текст предсказуем, его можно сжать. Раз он избыточен, он устойчив к шуму. Стёртая буква угадывается, опечатка исправляется, разговор можно понять в шумном поезде. Мы никогда не замечаем эту работу, потому что она не стоит нам усилий, но она целиком опирается на статистическую структуру языка, который мы выучили.
Вечерело, когда они наконец добрались до берега озера. Вода была неподвижной и отражала тёмные горы. Они положили рюкзаки на траву, сели рядом и несколько минут молчали. Ветер стих. Заброшенная лодка тихо стучала о деревянный причал. Позже, когда ночь стала полной, они разожгли маленький костёр и смотрели, как искры поднимаются к звёздам.
Преподаватель написал на доске три строки и повернулся к классу. Никто ещё не понимал, и это было нормально. Он начал сначала, медленнее, с простого примера. Одна студентка подняла руку и задала вопрос, который молча задавали себе все. Ответ сразу осветил всё рассуждение. Стало слышно, как несколько ручек одновременно снова начали писать.
Память работает примерно так же. Мы храним не каждую подробность, мы храним структуру и восстанавливаем остальное. Поэтому мы помним смысл фразы долго после того, как забыли её точные слова. Мы сохраняем не текст, а то, что было в тексте непредсказуемого. Остальное грамматика восстанавливает сама.
Дождь шёл уже три дня, и дорога стала непроходимой. Жители посёлка ждали без нетерпения, привыкшие к таким временам. Они одалживали друг другу дрова, делились супом, разговаривали у окна, глядя, как вода стекает по тропинке. Почтальон больше не поднимался. Радио обещало улучшение на следующий день, но никто по-настоящему не верил.
То, что мы называем пониманием фразы, возможно, прежде всего есть способность предвидеть её продолжение. Статистическая модель, обученная предсказывать следующее слово, в итоге представляет, хотя её об этом не просили, грамматику, словарь, обороты речи и даже некоторые знания о мире. Предсказание не скромная задача: вероятно, это самая требовательная из всех, потому что чтобы предсказывать хорошо, надо знать почти всё о предшествующем тексте.
Ты идёшь с нами или остаёшься здесь, спросила она, закрывая сумку. Я ещё не знаю, ответил он, не поднимая головы. Решай быстрее, автобус уходит через четверть часа, а другого не будет до завтрашнего утра. Он посмотрел на окно, потом на стол, потом на свои руки. Хорошо, сказал он наконец, я иду, но останусь ненадолго. Она улыбнулась, ничего не добавив, и подала ему пальто.
В теле человека около шестидесяти тысяч километров кровеносных сосудов. Каждый день сердце перекачивает почти семь тысяч литров крови, без отдыха, всю жизнь. Лёгкие обменивают кислород и углекислый газ через поверхность, сравнимую с теннисным кортом. Эти числа всегда удивляют, но они описывают совершенно обычную работу тела любого человека, идущего по улице.
Городской совет собрался в четверг вечером, чтобы рассмотреть бюджет следующего года. Работы на центральной площади, которые долго откладывали, должны начаться весной. Несколько жителей пришли задать вопросы о парковке и о закрытии маленькой школы. Мэр обещал провести общественное собрание до конца месяца. Заседание закончилось немного позже десяти часов.
Возьмите триста граммов муки, щепотку соли, два яйца и половину литра молока. Сначала смешайте муку и соль, сделайте углубление в середине, разбейте туда яйца и медленно размешивайте, понемногу вливая молоко. Дайте тесту постоять час в прохладном месте. Разогрейте сковороду, слегка смажьте её и налейте небольшой половник, поворачивая запястье, чтобы тесто растеклось.
Океаны покрывают более двух третей поверхности планеты и поглощают значительную часть тепла, накопленного в атмосфере. Их температура растёт медленно, но неуклонно, и это меняет течения, смещает косяки рыбы и ослабляет рифы. Учёные измеряют эти изменения с буёв, судов и спутников, а затем сравнивают результаты с всё более точными численными моделями.
Представьте себе очень большую книгу, в которой записаны все возможные фразы. Большинство из них было бы бессмыслицей, некоторые были бы грамматически правильными, и лишь ничтожная часть имела бы смысл. Писать значит двигаться по этой книге узкими тропами. Именно эти тропы, а не сами слова, статистика и умеет описывать.
Поезд ушёл в семь часов утра. На перроне было ещё темно, и лампы бросали жёлтый свет на мокрый бетон. Человек десять ждали молча, подняв воротники и спрятав руки в карманы. Когда двери открылись, все вошли не спеша. Через час прошёл контролёр, посмотрел билеты, ничего не сказал и вернулся в начало поезда. За окном тянулись поля, серые и плоские, разрезанные рядами голых деревьев. Женщина читала газету, мужчина спал, прислонив голову к стеклу, ребёнок каждые пять минут спрашивал, сколько ещё осталось.
Всю неделю шёл дождь, и сад стал непроходимым. Земля липнет к обуви, дорожки исчезли под водой, а розы, которые мы подрезали в феврале, только начинают оживать. Отец говорил, что саду нужно терпение, а не сила. Он проводил воскресенья, копая, сажая, глядя, как растёт то, что зацветёт только на следующий год. Я понял гораздо позже, что он находил в этой медлительности. Сегодня я делаю то же самое, теми же инструментами, в том же беспорядке, и меня это вполне устраивает.
Кухня — это комната, где в итоге собираются все. Заходишь выпить стакан воды и остаёшься на час. Там стол, разные стулья, шум холодильника, окно во двор. Именно там говорят о важном, почти всегда вскользь, между двумя движениями, пока кто-то чистит овощи или вытирает тарелку. Никто никогда не садится, чтобы объявить новость. Её вставляют в разговор, ждут реакции и продолжают резать лук.
Тело хранит память движений долго после того, как голова их забыла. Садишься на велосипед через пятнадцать лет, и равновесие возвращается через три метра. Находишь клавиатуру, и пальцы знают, куда идти, раньше, чем ты подумал о буквах. Эта память не проходит через слова. Она устанавливается повторением, сопротивляется забыванию и объясняет, почему учиться медленно часто лучше, чем быстро.
Цифры прошлого месяца показывают умеренный рост потребления, прежде всего за счёт услуг. Промышленность остаётся стабильной, строительство немного снижается третий квартал подряд. Цены продолжают расти, но медленнее, чем в начале года. Опрошенные экономисты осторожны: они напоминают, что эти колебания невелики, что пересмотры случаются часто и что нужно несколько кварталов, прежде чем говорить о тенденции.
Есть два способа слушать музыку. Можно включить её фоном во время работы и позволить ей занимать пространство, не думая о ней. А можно сесть, не делать ничего другого и следить за тем, что происходит. Второй способ требует усилия, которое мы делаем всё реже. И всё же только он позволяет услышать, как построена пьеса, повторы, паузы, тот момент, когда инструмент вступает, когда его уже не ждали.
Гора полностью меняется в зависимости от часа. Утром воздух чистый, гребни очерчены, видно на тридцать километров. К полудню всё становится плоским, цвета выцветают, от камней поднимается жар. Вечером тень поднимается по склонам, и вершины остаются освещёнными долго после того, как долина ушла в синеву. Те, кто выходит рано, это знают: один и тот же подъём совсем не одно и то же в шесть и в четырнадцать часов.
Хороший преподаватель не даёт ответа. Он задаёт вопрос, который позволяет его найти, и потом ждёт. Это ожидание — самая трудная часть работы, потому что оно похоже на бездействие, а на самом деле и есть работа. Объяснить слишком быстро значит лишить ученика единственного важного момента, когда что-то само встаёт на место. Кажется, что выигрываешь время, а на деле его теряют.
Сон занимает треть нашей жизни, и мы до сих пор не знаем точно, зачем он нужен. Известно одно: отнять у него несколько часов — и внимание, настроение и память заметно ухудшаются уже на следующий день. Ночью мозг не выключается: он проигрывает, сортирует, закрепляет. Воспоминания дня пересматриваются, сравниваются, иногда стираются. Мы просыпаемся с упрощённой версией вчерашнего.
То, что мы называем привычкой, — это решение, которое мы больше не принимаем. Сначала надо об этом думать, заставлять себя, сопротивляться желанию заняться другим. Потом движение закрепляется, умственная цена падает, и однажды замечаешь, что сделал это не думая. Поэтому привычки так трудно менять: не воли не хватает, а того, что решение перестало быть осознанным.
Субботний рынок начинается в семь и пустеет к часу дня. Производители приезжают первыми, разгружают ящики, ставят весы. К девяти уже толпа, люди пересекаются, здороваются, стоят в очереди у одних и тех же трёх прилавков. Цены указаны не везде, и никто не жалуется. К полудню непроданное начинает дешеветь, и завсегдатаи ждут именно этого момента, чтобы купить.
Учить иностранный язык — значит согласиться долго говорить плохо. Этот период неприятен и обязателен. Мы понимаем раньше, чем говорим, читаем раньше, чем пишем, узнаём раньше, чем производим. Быстрее продвигаются не те, у кого лучше память, а те, кто допускает больше ошибок. Каждая неудачная фраза немного исправляет внутреннюю модель, которую мы строим сами того не зная.
Северный свет ровный, южный меняется весь день. Художники знают это всегда и выбирают мастерские соответственно. Окно на север даёт ровный, чуть холодный свет, который не движется с десяти до четырёх. На юге приходится фильтровать, подстраивать, начинать заново. Эта строительная деталь определила расположение тысяч мастерских за четыре века.
Часто говорят, что картинка стоит тысячи слов. Это верно для описания лица и совершенно неверно для выражения условия, отрицания или сомнения. Никакая картинка не говорит если, ни ещё нет, ни разве что. Язык изобрёл средства, которых нет у рисунка, и поэтому мы не переставали писать, хотя рисовать умели гораздо раньше.`
};

/* ------------------------------------------------------------
   Jeu de DÉVELOPPEMENT : sert uniquement à régler les poids
   d'interpolation du modèle. Distinct du jeu de test, sinon les
   chiffres annoncés seraient optimistes — on aurait choisi les
   réglages qui flattent la mesure.
   ------------------------------------------------------------ */
export const DEV = {
  fr: `La bibliothèque ferme à dix-neuf heures, sauf le jeudi. Nous avons pris deux livres et une carte de la région, puis nous sommes ressortis dans le froid. Il n'y avait presque personne dans la rue. Un chien attendait devant une porte, patient, la neige sur le dos.
Quand on écrit une lettre à la main, on ne peut pas revenir en arrière sans que cela se voie. Cette contrainte oblige à penser la phrase avant de la commencer. Beaucoup de gens trouvent que leurs lettres manuscrites sont mieux construites que leurs messages électroniques, et ils ont probablement raison.
Le moteur a démarré au troisième essai. Nous avons roulé jusqu'au village voisin pour acheter du pain et des allumettes. Sur le chemin du retour, la pluie a repris et la route est devenue glissante. Il a fallu ralentir et allumer les phares en plein après-midi.
Les enfants ont couru vers la mer sans écouter personne. L'eau était froide, ils sont ressortis tout de suite, ils y sont retournés cinq minutes plus tard. Nous les regardions depuis les rochers en buvant du café tiède dans des gobelets en carton.`,

  en: `The library closes at seven, except on Thursdays. We took two books and a map of the region, then went back out into the cold. There was almost nobody in the street. A dog waited in front of a door, patient, with snow on its back.
When you write a letter by hand you cannot go back without it showing. That constraint forces you to think the sentence through before starting it. Many people find their handwritten letters better built than their electronic messages, and they are probably right.
The engine started on the third try. We drove to the next village to buy bread and matches. On the way back the rain started again and the road became slippery. We had to slow down and put the lights on in the middle of the afternoon.
The children ran towards the sea without listening to anyone. The water was cold, they came straight back out, they went in again five minutes later. We watched them from the rocks, drinking lukewarm coffee from paper cups.`,

  es: `La biblioteca cierra a las siete, salvo los jueves. Cogimos dos libros y un mapa de la región y salimos otra vez al frío. No había casi nadie en la calle. Un perro esperaba delante de una puerta, paciente, con nieve en el lomo.
Cuando escribes una carta a mano no puedes volver atrás sin que se note. Esa limitación obliga a pensar la frase antes de empezarla. Mucha gente encuentra que sus cartas manuscritas están mejor construidas que sus mensajes electrónicos, y probablemente tienen razón.
El motor arrancó al tercer intento. Fuimos hasta el pueblo vecino a comprar pan y cerillas. A la vuelta empezó a llover otra vez y la carretera se puso resbaladiza. Hubo que ir más despacio y encender los faros en plena tarde.
Los niños corrieron hacia el mar sin escuchar a nadie. El agua estaba fría, salieron enseguida y volvieron a entrar cinco minutos después. Los mirábamos desde las rocas bebiendo café tibio en vasos de cartón.`,

  ru: `Библиотека закрывается в семь, кроме четверга. Мы взяли две книги и карту области и снова вышли на холод. На улице почти никого не было. Собака ждала перед дверью, терпеливая, со снегом на спине.
Когда пишешь письмо от руки, нельзя вернуться назад незаметно. Это ограничение заставляет продумать фразу до того, как её начать. Многие находят, что их рукописные письма построены лучше электронных сообщений, и они, вероятно, правы.
Мотор завёлся с третьей попытки. Мы доехали до соседней деревни купить хлеба и спичек. На обратном пути снова пошёл дождь, и дорога стала скользкой. Пришлось сбавить скорость и включить фары среди дня.
Дети побежали к морю, никого не слушая. Вода была холодная, они сразу вышли и через пять минут вернулись обратно. Мы смотрели на них со скал, попивая тёплый кофе из картонных стаканчиков.`
};

/* Textes de contrôle : jamais utilisés pour estimer les probabilités
   ni pour régler quoi que ce soit. Tous les chiffres annoncés dans
   l'application sont mesurés ici. */
export const TEST = {
  fr: `Le train entra en gare avec dix minutes de retard. Sur le quai, une poignée de voyageurs attendaient en regardant l'horloge. Un homme portait deux valises trop lourdes et cherchait un chariot. Une mère tenait la main de son fils qui voulait absolument voir la locomotive. Quand les portes s'ouvrirent, tout le monde avança en même temps.
Nous avons souvent l'impression de choisir librement chaque mot que nous écrivons. Pourtant, dès que la phrase est commencée, le nombre de suites acceptables diminue très vite. La grammaire élimine des milliers de possibilités, le sens en élimine d'autres, l'habitude fait le reste. Ce qui reste au moment d'écrire le mot suivant est souvent une poignée de candidats, parfois un seul.
La cuisine sentait le citron et le beurre chaud. Elle cassa les œufs un par un, sépara les blancs, ajouta le sucre et commença à battre sans se presser. Par la fenêtre on voyait le jardin détrempé et le vieux pommier qui perdait ses dernières feuilles.
La réunion a duré deux heures de plus que prévu. Personne n'a osé le dire mais tout le monde le pensait. À la fin, la décision prise était exactement celle qui figurait dans le document envoyé la veille.
Un ami m'a demandé pourquoi je continuais à noter mes dépenses à la main. Je lui ai répondu que le geste d'écrire le montant me faisait sentir la somme, ce qu'aucune application ne réussit à produire.
Le chat de la voisine passe par le toit et entre par la fenêtre de la cuisine. Il s'installe sur la chaise la plus proche du radiateur, dort trois heures et repart sans prévenir.`,

  en: `The train pulled into the station ten minutes late. On the platform a handful of travellers waited, watching the clock. A man carried two suitcases that were far too heavy and looked around for a trolley. A mother held the hand of her son, who absolutely wanted to see the locomotive. When the doors opened everyone moved forward at once.
We often feel that we freely choose every word we write. Yet as soon as the sentence has begun, the number of acceptable continuations falls very quickly. Grammar rules out thousands of possibilities, meaning rules out more, and habit does the rest. What remains when the next word is due is often a handful of candidates, sometimes only one.
The kitchen smelled of lemon and warm butter. She broke the eggs one by one, separated the whites, added the sugar and began to beat without hurrying. Through the window you could see the soaked garden and the old apple tree losing its last leaves.
The meeting ran two hours longer than planned. Nobody dared say it but everyone was thinking it. In the end the decision taken was exactly the one written in the document sent the day before.
A friend asked me why I still write down my expenses by hand. I answered that the act of writing the amount makes me feel the sum, which no application manages to produce.
The neighbour's cat comes over the roof and in through the kitchen window. It settles on the chair nearest the radiator, sleeps three hours and leaves without warning.`,

  es: `El tren entró en la estación con diez minutos de retraso. En el andén un puñado de viajeros esperaba mirando el reloj. Un hombre llevaba dos maletas demasiado pesadas y buscaba un carrito. Una madre sostenía la mano de su hijo, que quería ver la locomotora a toda costa. Cuando se abrieron las puertas todos avanzaron a la vez.
A menudo tenemos la impresión de elegir libremente cada palabra que escribimos. Sin embargo, en cuanto la frase ha empezado, el número de continuaciones aceptables disminuye muy deprisa. La gramática elimina miles de posibilidades, el sentido elimina otras, la costumbre hace el resto. Lo que queda en el momento de escribir la palabra siguiente suele ser un puñado de candidatas, a veces una sola.
La cocina olía a limón y a mantequilla caliente. Rompió los huevos uno a uno, separó las claras, añadió el azúcar y empezó a batir sin prisa. Por la ventana se veía el jardín empapado y el viejo manzano que perdía sus últimas hojas.
La reunión duró dos horas más de lo previsto. Nadie se atrevió a decirlo pero todos lo pensaban. Al final la decisión tomada fue exactamente la que figuraba en el documento enviado la víspera.
Un amigo me preguntó por qué sigo anotando mis gastos a mano. Le respondí que el gesto de escribir la cantidad me hace sentir la suma, cosa que ninguna aplicación consigue producir.
El gato de la vecina pasa por el tejado y entra por la ventana de la cocina. Se instala en la silla más cercana al radiador, duerme tres horas y se va sin avisar.`,

  ru: `Поезд прибыл на вокзал с опозданием на десять минут. На перроне несколько пассажиров ждали, поглядывая на часы. Мужчина нёс два слишком тяжёлых чемодана и искал тележку. Мать держала за руку сына, который непременно хотел увидеть локомотив. Когда двери открылись, все двинулись вперёд одновременно.
Нам часто кажется, что мы свободно выбираем каждое слово. Но как только фраза началась, число допустимых продолжений очень быстро уменьшается. Грамматика убирает тысячи возможностей, смысл убирает другие, привычка делает остальное. К моменту, когда нужно написать следующее слово, обычно остаётся горстка кандидатов, иногда только один.
На кухне пахло лимоном и горячим маслом. Она разбила яйца одно за другим, отделила белки, добавила сахар и начала не спеша взбивать. Через окно был виден промокший сад и старая яблоня, терявшая последние листья.
Совещание длилось на два часа дольше, чем планировалось. Никто не решился сказать это вслух, но думали все. В конце принятое решение было ровно тем, что стояло в документе, присланном накануне.
Друг спросил меня, почему я до сих пор записываю расходы от руки. Я ответил, что сам жест написания суммы даёт её почувствовать, чего не удаётся ни одному приложению.
Кошка соседки проходит по крыше и входит через кухонное окно. Она устраивается на стуле поближе к батарее, спит три часа и уходит не предупредив.`
};

/* ============================================================
   Les échantillons publiés par Shannon (1948, §3), reproduits
   pour comparaison directe avec ceux que produit notre modèle.
   ============================================================ */
export const SHANNON_1948 = [
  { order: 0, label: 'Zero-order approximation', desc: 'symboles indépendants et équiprobables',
    text: 'XFOML RXKHRJFFJUJ ZLPWCFWKCYJ FFJEYVKCQSGHYD QPAAMKBZAACIBZLHJQD' },
  { order: 1, label: 'First-order approximation', desc: 'fréquences des lettres de l\'anglais',
    text: 'OCRO HLI RGWR NMIELWIS EU LL NBNESEBYA TH EEI ALHENHTTPA OOBTTVA NAH BRL' },
  { order: 2, label: 'Second-order approximation', desc: 'structure des digrammes',
    text: 'ON IE ANTSOUTINYS ARE T INCTORE ST BE S DEAMY ACHIN D ILONASIVE TUCOOWE AT TEASONARE FUSO TIZIN ANDY TOBE SEACE CTISBE' },
  { order: 3, label: 'Third-order approximation', desc: 'structure des trigrammes',
    text: 'IN NO IST LAT WHEY CRATICT FROURE BIRS GROCID PONDENOME OF DEMONSTURES OF THE REPTAGIN IS REGOACTIONA OF CRE' },
  { order: 'w1', label: 'First-order word approximation', desc: 'mots tirés selon leur fréquence',
    text: 'REPRESENTING AND SPEEDILY IS AN GOOD APT OR COME CAN DIFFERENT NATURAL HERE HE THE A IN CAME THE TO OF TO EXPERT GRAY COME TO FURNISHES THE LINE MESSAGE HAD BE THESE' },
  { order: 'w2', label: 'Second-order word approximation', desc: 'probabilités de transition entre mots',
    text: 'THE HEAD AND IN FRONTAL ATTACK ON AN ENGLISH WRITER THAT THE CHARACTER OF THIS POINT IS THEREFORE ANOTHER METHOD FOR THE LETTERS THAT THE TIME OF WHO EVER TOLD THE PROBLEM FOR AN UNEXPECTED' }
];

/** Statistiques descriptives d'un corpus (affichage). */
export function corpusStats(text) {
  const words = text.split(/\s+/).filter(Boolean);
  return { chars: text.length, words: words.length, types: new Set(words.map(w => w.toLowerCase())).size };
}
